-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 18:43:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema infotech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infotech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infotech` DEFAULT CHARACTER SET utf8 ;
USE `infotech` ;

-- -----------------------------------------------------
-- Table `infotech`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotech`.`usuarios` (
  `idUsu` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` ENUM('C', 'A') NOT NULL,
  PRIMARY KEY (`idUsu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `infotech`.`ordemdeservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotech`.`ordemdeservico` (
  `idOs` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `probInfor` VARCHAR(500) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `probConst` VARCHAR(500) NOT NULL,
  `data` DATE NOT NULL,
  `osIdUsu` INT(11) NOT NULL,
  PRIMARY KEY (`idOs`, `osIdUsu`),
  INDEX `fk_OrdemDeServico_Usuarios_idx` (`osIdUsu` ASC),
  CONSTRAINT `fk_OrdemDeServico_Usuarios`
    FOREIGN KEY (`osIdUsu`)
    REFERENCES `infotech`.`usuarios` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `infotech`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotech`.`imagens` (
  `idImagens` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL,
  `tipo` ENUM('C', 'A') NOT NULL,
  `imIdOs` INT(11) NOT NULL,
  PRIMARY KEY (`idImagens`, `imIdOs`),
  INDEX `fk_Imagens_OrdemDeServico1_idx` (`imIdOs` ASC),
  CONSTRAINT `fk_Imagens_OrdemDeServico1`
    FOREIGN KEY (`imIdOs`)
    REFERENCES `infotech`.`ordemdeservico` (`idOs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `infotech` ;

-- -----------------------------------------------------
-- function function_cadastraOrdemDeServico
-- -----------------------------------------------------

DELIMITER $$
USE `infotech`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `function_cadastraOrdemDeServico`(
    fproduto VARCHAR(100),
    fmarca VARCHAR(45),
    fmodelo VARCHAR(100),
    fprobInfor VARCHAR(45),
    fstatus VARCHAR(45),
    fprobConst VARCHAR(45),
	fdata DATE,
    fosIdUsu INT) RETURNS int(11)
BEGIN
	INSERT INTO `ordemdeservico`(`produto`, `marca`, `modelo`, `probInfor`, `status`, `probConst`, `data`, `osIdUsu`)
        values
        (fproduto,fmarca,fmodelo,fprobInfor,fstatus,fprobConst,fdata,fosIdUsu);
       return LAST_INSERT_ID();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function function_cadastraUsuarios
-- -----------------------------------------------------

DELIMITER $$
USE `infotech`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `function_cadastraUsuarios`(
    fnome VARCHAR(100),
    fcpf VARCHAR(45),
    fendereco VARCHAR(100),
    ftelefone VARCHAR(45),
    femail VARCHAR(45),
    fsenha VARCHAR(45),
    ftipo VARCHAR(1)) RETURNS int(11)
BEGIN
	INSERT INTO `usuarios`(`nome`, `cpf`, `endereco`, `telefone`, `email`, `senha`, `tipo`)
        values
        (fnome,fcpf,fendereco,ftelefone,femail,fsenha,ftipo);
       return LAST_INSERT_ID();
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
